name: Run clang-format Linter

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          clangFormatVersion: 12
          inplace: True
      - name: astyle checks
        run: |
          sudo apt update
          sudo apt install astyle
          git diff --name-only --diff-filter=d origin/${GITHUB_BASE_REF} \
            | ( grep '.*\.\(c\|cpp\|h\|hpp\)$' || true ) \
            | ( grep -v -f .codecheckignore || true ) \
            | while read file; do astyle -n --options=.astylerc "${file}"; done
          git diff --exit-code --diff-filter=d --color
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: "[update] clang-format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
